import type { LinksFunction, MetaFunction } from 'remix';
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from 'remix';
import Footer from './layouts/Footer';
import Header from './layouts/Header';
import SideNav from './layouts/SideNav';
// this will autogenerated
import reset from './reset.css';
import styles from './windi.css';

export const meta: MetaFunction = () => {
  return { title: 'Mocchapine | Rayhan Hamada' };
};

export const links: LinksFunction = () => {
  return [
    {
      rel: 'stylesheet',
      href: reset,
    },

    {
      rel: 'stylesheet',
      href: styles,
    },
  ];
};

export default function App() {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body className="font-mono bg-[#303030] min-h-screen flex flex-col justify-between">
        <Header />
        <SideNav />
        <Outlet />
        <Footer />
        <ScrollRestoration />
        <Scripts />
        {process.env.NODE_ENV === 'development' && <LiveReload />}
      </body>
    </html>
  );
}
